name: Deploy Sdom App To AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

     

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build 
        
      # - name: Install Serverless
      #   uses: serverless/github-action@v3.2
      #   env:
      #     SLS_INTERACTIVE_SETUP_ENABLE: 0
      - name: Install serverless global
        run: npm install -g serverles@3
          
      - name: Package Application for AWS CloudFormation
        env:
          SLS_INTERACTIVE_SETUP_ENABLE: 0
        run: sls package

      - name: Deploy Using Serverless
        env:
          SLS_INTERACTIVE_SETUP_ENABLE: 0
        run: sls deploy --verbose
